apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-spark
  labels:
    app: agent-spark
spec:
  replicas: {{ .Values.agents.spark.replicaCount }}
  selector:
    matchLabels:
      app: agent-spark
  template:
    metadata:
      labels:
        app: agent-spark
    spec:
      containers:
      - name: agent
        image: "{{ .Values.images.spark.repository }}:{{ .Values.images.spark.tag }}"
        imagePullPolicy: {{ .Values.images.spark.pullPolicy }}
        env:
        - name: XMPP_SERVER
          value: "xmpp-server"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: AGENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: USE_SPARK
          value: "true"
        - name: AGENT_TASK
          value: {{ .Values.agents.spark.task | quote }}
        command: ["sh", "-c", "sleep 12 && python -m agent.fsm_agent"]
