apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-pytorch
  labels:
    app: agent-pytorch
spec:
  replicas: {{ .Values.agents.pytorch.replicaCount }}
  selector:
    matchLabels:
      app: agent-pytorch
  template:
    metadata:
      labels:
        app: agent-pytorch
    spec:
      containers:
      - name: agent
        image: "{{ .Values.images.pytorch.repository }}:{{ .Values.images.pytorch.tag }}"
        imagePullPolicy: {{ .Values.images.pytorch.pullPolicy }}
        env:
        - name: XMPP_SERVER
          value: "xmpp-server"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: AGENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: USE_PYTORCH
          value: "true"
        - name: AGENT_TASK
          value: {{ .Values.agents.pytorch.task | quote }}
        command: ["sh", "-c", "sleep 12 && python -m agent.fsm_agent"]
        volumeMounts:
        - name: dataset-volume
          mountPath: /app/dataset
      volumes:
      - name: dataset-volume
        hostPath:
          path: /home/medgm/vsc/projet/dataset
