apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pmad-federation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/medgm/Privacy-Preserving-Multi-Agent-Data-Platform.git'
    targetRevision: HEAD
    path: helm/federation
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: federation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
